version: '2'
services:
    jhipstertest2-app:
        image: jhipstertest2
        external_links:
            - jhipstertest2-mariadb:mariadb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/jhipstertest2
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipstertest2-mariadb:
        extends:
            file: mariadb.yml
            service: jhipstertest2-mariadb
