version: '2'
services:
    jhipstertest2-mariadb:
        container_name: jhipstertest2-mariadb
        image: mariadb:10.1.17
        # volumes:
        #     - ~/volumes/jhipster/jhipstertest2/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=jhipstertest2
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
